2018/04/04 20:56:40 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:41 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:42 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:49 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.ph HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:56:51 [crit] 246#246: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:02 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:02 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:03 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:04 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:05 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 20:59:13 [crit] 246#246: *10 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:00:53 [crit] 246#246: *30 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:00:54 [crit] 246#246: *30 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:00:55 [crit] 246#246: *30 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:18 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:18 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:19 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:19 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:19 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:02:22 [crit] 246#246: *35 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "advanced.test"
2018/04/04 21:04:15 [error] 822#822: *6 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:15 [error] 822#822: *6 FastCGI sent in stderr: "GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:44 [error] 822#822: *6 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:44 [error] 822#822: *6 FastCGI sent in stderr: "GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:52 [error] 822#822: *6 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:04:52 [error] 822#822: *6 FastCGI sent in stderr: "GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /user/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 21:24:33 [error] 1040#1040: *10 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /debug/default/toolbar?tag=5ac5266b87e1e HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/hello"
2018/04/04 22:10:43 [error] 3644#3644: *90 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /chat HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 22:20:07 [error] 3644#3644: *236 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:33
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /signup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/04 22:20:07 [error] 3644#3644: *236 FastCGI sent in stderr: " Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /signup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 11:53:28 [error] 2944#2944: *296 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Arra" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /pjax-demo/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 11:53:28 [error] 2944#2944: *296 FastCGI sent in stderr: "y)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /pjax-demo/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:08:36 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project/create-modal HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:08:53 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:08:56 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:09:00 [error] 2941#2941: *465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare frontend\controllers\ProjectController::actionCreateModal() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/ProjectController.php on line 97" while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /project/create HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/"
2018/04/07 12:13:44 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:13:48 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:13:52 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:14:07 [error] 2941#2941: *493 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 81. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/?id=test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/07 12:48:06 [error] 2944#2944: *810 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /debug/default/toolbar?tag=5ac8a1e19589c HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/project/index"
2018/04/08 17:32:33 [error] 56#56: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:33:46 [error] 56#56: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:33:56 [error] 56#56: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:17 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:18 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:23 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:40 [error] 748#748: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:34:49 [error] 828#828: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:35:13 [error] 828#828: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/08 17:37:22 [error] 930#930: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/11 22:41:40 [error] 514#514: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:42:40 [error] 334#334: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: advanced.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:54:18 [error] 338#338: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advan" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/singup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:54:18 [error] 338#338: *64 FastCGI sent in stderr: "ced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/singup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:54:20 [error] 338#338: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advan" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/singup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:54:20 [error] 338#338: *64 FastCGI sent in stderr: "ced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/singup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:54:46 [error] 338#338: *64 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/singup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 11:54:46 [error] 338#338: *64 FastCGI sent in stderr: "')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/singup HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:05:52 [error] 730#730: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm P" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:05:52 [error] 730#730: *1 FastCGI sent in stderr: "rojects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:05:59 [error] 730#730: *3 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /m" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:05:59 [error] 730#730: *3 FastCGI sent in stderr: "nt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:06:10 [error] 730#730: *5 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /m" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:06:10 [error] 730#730: *5 FastCGI sent in stderr: "nt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:07:22 [error] 823#823: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:07:41 [error] 823#823: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:07:58 [error] 823#823: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:07:59 [error] 823#823: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test", referrer: "http://api.test/"
2018/04/15 17:08:16 [error] 823#823: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:08:48 [error] 823#823: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/test HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:08:52 [error] 823#823: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:08:55 [error] 823#823: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  array_merge(): Argument #3 is not an array in /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/config/main.php on line 7
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:18:25 [error] 823#823: *33 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /m" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:18:25 [error] 823#823: *33 FastCGI sent in stderr: "nt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:18:36 [error] 823#823: *35 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Array)
#5 /mnt/e/PHP Storm P" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /api HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:18:36 [error] 823#823: *35 FastCGI sent in stderr: "rojects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /api HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:18:54 [error] 823#823: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
Error: Call to a member function toArray() on null in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/views/layouts/main.php:32
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/mnt/e/PHP Stor...', Array)
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/mnt/e/PHP Stor...', Array, Object(frontend\controllers\SiteController))
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('<div class="sit...')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(139): yii\base\Controller->render('error', Arra" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /api/v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:18:54 [error] 823#823: *37 FastCGI sent in stderr: "y)
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorAction.php(118): yii\w" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /api/v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/15 17:23:35 [error] 886#886: *1 directory index of "/mnt/e/PHP Storm Projects/GU/yii2-advanced/" is forbidden, client: 127.0.0.1, server: tade4ex.test, request: "GET / HTTP/1.1", host: "tade4ex.test"
2018/04/15 17:23:41 [error] 886#886: *1 directory index of "/mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/" is forbidden, client: 127.0.0.1, server: tade4ex.test, request: "GET /frontend/ HTTP/1.1", host: "tade4ex.test"
2018/04/15 17:26:30 [error] 886#886: *5 directory index of "/mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/" is forbidden, client: 127.0.0.1, server: tade4ex.test, request: "GET /frontend/ HTTP/1.1", host: "tade4ex.test"
2018/04/15 17:26:32 [error] 886#886: *5 directory index of "/mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/" is forbidden, client: 127.0.0.1, server: tade4ex.test, request: "GET /frontend/ HTTP/1.1", host: "tade4ex.test"
2018/04/15 17:29:02 [error] 961#961: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Yii' not found in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php:197
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/web/index.php(14): yii\base\Application->__construct(Array)
#1 {main}
  thrown in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php on line 197" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:29:03 [error] 961#961: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Yii' not found in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php:197
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/web/index.php(14): yii\base\Application->__construct(Array)
#1 {main}
  thrown in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php on line 197" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:29:03 [error] 961#961: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Yii' not found in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php:197
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/web/index.php(14): yii\base\Application->__construct(Array)
#1 {main}
  thrown in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php on line 197" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:29:03 [error] 961#961: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Yii' not found in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php:197
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/web/index.php(14): yii\base\Application->__construct(Array)
#1 {main}
  thrown in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php on line 197" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET /v1/project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:43:21 [error] 350#350: *10 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Request.php:284
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:43:24 [error] 350#350: *37 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Request.php:284
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:43:30 [error] 350#350: *39 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Request.php:284
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:43:50 [error] 350#350: *10 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\web\NotFoundHttpException: Page not found. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Request.php:284
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Application.php(82): yii\web\Request->resolve()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 17:46:44 [error] 349#349: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122
PHP message: PHP Fatal error:  Uncaught yii\base\InvalidConfigException: The "id" configuration for the Application is required. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php:220
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php(202): yii\base\Application->preInit(Array)
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/web/index.php(17): yii\base\Application->__construct(Array)
#2 {main}
  thrown in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Application.php on line 220" while reading response header from upstream, client: 127.0.0.1, server: api.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 18:00:15 [error] 349#349: *40 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\UnknownClassException: Unable to find 'api\controllers\SiteController' in file: /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/controllers/SiteController.php. Namespace missing? in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/BaseYii.php:296
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('api\\controllers...')
#1 [internal function]: spl_autoload_call('api\\controllers...')
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(637): class_exists('api\\controllers...')
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(596): yii\base\Module->createControllerByID('site')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('error')
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#6 /mnt/e/PHP Storm" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 18:02:16 [error] 349#349: *42 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\UnknownClassException: Unable to find 'api\controllers\SiteController' in file: /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/controllers/SiteController.php. Namespace missing? in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/BaseYii.php:296
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('api\\controllers...')
#1 [internal function]: spl_autoload_call('api\\controllers...')
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(637): class_exists('api\\controllers...')
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(596): yii\base\Module->createControllerByID('site')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('error')
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#6 /mnt/e/PHP Storm" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 18:02:21 [error] 349#349: *42 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\UnknownClassException: Unable to find 'api\controllers\SiteController' in file: /mnt/e/PHP Storm Projects/GU/yii2-advanced/api/controllers/SiteController.php. Namespace missing? in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/BaseYii.php:296
Stack trace:
#0 [internal function]: yii\BaseYii::autoload('api\\controllers...')
#1 [internal function]: spl_autoload_call('api\\controllers...')
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(637): class_exists('api\\controllers...')
#3 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(596): yii\base\Module->createControllerByID('site')
#4 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('error')
#5 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#6 /mnt/e/PHP Storm" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 18:22:51 [error] 349#349: *144 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\NotFoundHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\NotFoundHttpException))
#3 {main}
Previous exception:
yii\base\InvalidRouteException: Unable to resolve the request: project/1 in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Controller.php:128
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('1', Array)
#1 /mnt/e/PHP Storm Projects/GU/yii2-adv" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET /project/1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/15 18:34:55 [error] 353#353: *174 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request "site/error". in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(108): yii\base\Module->runAction('site/error')
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\UnauthorizedHttpException))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\UnauthorizedHttpException))
#3 {main}
Previous exception:
yii\web\UnauthorizedHttpException: Your request was made with invalid credentials. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/filters/auth/AuthMethod.php:93
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/filters/auth/AuthMethod.php(76): yii\filters\auth\AuthMethod->handleFailure(Obje" while reading upstream, client: 127.0.0.1, server: api.test, request: "GET /project HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "api.test"
2018/04/18 21:52:20 [error] 588#588: *1 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: advanced.test, request: "GET /task/view?id=5 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test"
2018/04/18 22:06:48 [error] 588#588: *76 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on line 84. in /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /mnt/e/PHP Storm Projects/GU/yii2-advanced/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /mnt/e/PHP Storm Projects/GU/yii2-advanced/frontend/controllers/SiteController.php on li" while reading upstream, client: 127.0.0.1, server: advanced.test, request: "GET /site/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "advanced.test", referrer: "http://advanced.test/task/view?id=4"
